'use client';
import BusyLabel from './busy-label';
import {useState,useTransition,type FormEvent} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {HeartHandshake} from 'lucide-react';
import {followupLogin,followupRecover,followupPassword} from '@/app/seguimiento/login/actions';
import {button,input,label,ErrorNotice,Notice} from './ui';
export default function FollowupAuthForm({passwordMode=false}:{passwordMode?:boolean}){
 const router=useRouter();const [navigating,startNavigation]=useTransition();const [recover,setRecover]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy||navigating)return;setError('');setMessage('');const f=new FormData(e.currentTarget),email=String(f.get('email')??'').trim(),password=String(f.get('password')??'');if(passwordMode&&password!==f.get('confirm')){setError('Las contraseñas no coinciden.');return;}setBusy(true);
 try{const r=passwordMode?await followupPassword(password):recover?await followupRecover(email):await followupLogin({email,password});if('error'in r){setError(r.error??'No se pudo completar la operación.');return;}if(recover)setMessage('Si el correo está registrado, recibirás un enlace para restablecer tu contraseña.');else{startNavigation(()=>{router.replace('/seguimiento');router.refresh();});}}catch{setError('No se pudo conectar. Inténtalo de nuevo.');}finally{setBusy(false);}}
 return <main className="grid min-h-dvh place-items-center p-5"><section className="w-full max-w-md rounded-2xl border border-slate-200 bg-white p-7 shadow-sm sm:p-9"><Link href="/" className="mb-9 flex items-center gap-3 text-xl font-bold text-primary"><HeartHandshake size={34}/><span>Acompañar<small className="block text-xs font-normal tracking-widest">MMM CHILE</small></span></Link><h1 className="text-2xl font-bold text-primary">{passwordMode?'Define tu contraseña':recover?'Recupera tu acceso':'Bienvenido al equipo'}</h1><p className="mb-7 mt-3 text-slate-500">{passwordMode?'Usa al menos 12 caracteres.':'Accede con el correo con el que te invitó el supervisor.'}</p><form onSubmit={submit}><fieldset disabled={busy||navigating} className="grid gap-5">{!passwordMode&&<label className={label}>Correo electrónico<input className={input} name="email" type="email" autoComplete="email" required/></label>}{!recover&&<label className={label}>Contraseña<input className={input} name="password" type="password" autoComplete={passwordMode?'new-password':'current-password'} minLength={passwordMode?12:1} maxLength={128} required/></label>}{passwordMode&&<label className={label}>Repite la contraseña<input className={input} name="confirm" type="password" autoComplete="new-password" minLength={12} maxLength={128} required/></label>}<ErrorNotice message={error}/>{message&&<Notice>{message}</Notice>}<button className={button} disabled={busy||navigating} aria-busy={busy||navigating}>{busy||navigating?<BusyLabel>{navigating?'Abriendo seguimiento…':passwordMode?'Guardando contraseña…':recover?'Enviando enlace…':'Iniciando sesión…'}</BusyLabel>:passwordMode?'Guardar contraseña':recover?'Enviar enlace':'Iniciar sesión'}</button></fieldset></form>{!passwordMode&&<button disabled={busy||navigating} className="disabled:opacity-50 mt-5 w-full text-center text-sm font-semibold text-primary" onClick={()=>{setRecover(!recover);setError('');setMessage('');}}>{recover?'Volver al inicio de sesión':'Olvidé mi contraseña'}</button>}<p className="mt-7 border-t border-slate-100 pt-5 text-center text-sm text-slate-500">Acceso exclusivo por invitación.</p></section></main>;
}
