'use client';
import BusyLabel from './busy-label';
import {useEffect,useState,type FormEvent} from 'react';
import {getFollowupTeam,inviteFollowupMember,updateFollowupMember,cancelFollowupInvitation} from '@/app/seguimiento/actions';
import {categoryLabels,visitCategories,type Member} from '@/lib/seguimiento/records';
import {button,secondary,input,label,ErrorNotice,Notice,Modal,Badge} from './ui';
type Invitation={email:string;name:string;role:Member['role'];visit_category:Member['visit_category']};
export default function FollowupTeam({me,onChanged}:{me:Member;onChanged:()=>void}){
 const [members,setMembers]=useState<Member[]>([]),[invites,setInvites]=useState<Invitation[]>([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState('');
 const [form,setForm]=useState<Member|'new'|null>(null),[cancel,setCancel]=useState<string|null>(null),[busy,setBusy]=useState(false),[formError,setFormError]=useState(''),[notice,setNotice]=useState('');
 async function load(){setRefreshing(true);try{const r=await getFollowupTeam();if('error'in r){setError(r.error);return;}setMembers(r.members as Member[]);setInvites(r.invitations as Invitation[]);setError('');}catch{setError('No se pudo cargar el equipo.');}finally{setLoading(false);setRefreshing(false);}}
 useEffect(()=>{void load();},[]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!form||busy)return;const f=new FormData(e.currentTarget);setBusy(true);setFormError('');try{const r=form==='new'?await inviteFollowupMember({name:f.get('name'),email:f.get('email'),role:f.get('role'),category:f.get('category')||null}):await updateFollowupMember({id:form.id,role:form.id===me.id?form.role:f.get('role'),active:form.id===me.id?form.active:f.get('active')==='true',category:f.get('category')||null});if('error'in r)setFormError(r.error);else{setNotice('unassignedCount'in r&&r.unassignedCount?`Acceso guardado. ${r.unassignedCount} fichas quedaron pendientes de reasignación.`:'Acceso guardado.');setForm(null);onChanged();}await load();}catch{setFormError('No se pudo guardar. Inténtalo de nuevo.');}finally{setBusy(false);}}
 async function cancelAccess(){if(!cancel||busy)return;setBusy(true);setFormError('');try{const r=await cancelFollowupInvitation(cancel);if('error'in r)setFormError(r.error);else{setCancel(null);await load();}}catch{setFormError('No se pudo cancelar.');}finally{setBusy(false);}}
 return <section className="rounded-2xl border border-slate-200 bg-white"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-100 p-6"><div><h2 className="text-xl font-bold text-primary">Equipo de visitación</h2><p className="mt-1 text-sm text-slate-500">Accesos, roles e invitaciones.</p></div><button className={button} disabled={loading||refreshing||busy||!!error} onClick={()=>{setFormError('');setForm('new');}}>Invitar integrante</button></header><div className="p-6"><ErrorNotice message={error}/>{notice&&<Notice>{notice}</Notice>}{refreshing&&!loading&&<div className="mb-4 text-sm text-primary"><BusyLabel>Actualizando equipo…</BusyLabel></div>}{loading?<BusyLabel>Cargando equipo…</BusyLabel>:error?<button className={secondary} disabled={refreshing} onClick={()=>void load()}>{refreshing?<BusyLabel>Cargando…</BusyLabel>:"Reintentar"}</button>:<div className="divide-y divide-slate-100">{members.map(m=><article key={m.id} className="flex flex-wrap items-center justify-between gap-4 py-4"><div><h3 className="font-bold">{m.name}{m.id===me.id?' (tú)':''}</h3><p className="break-all text-sm text-slate-500">{m.email}</p><p className="text-sm text-slate-500">{m.visit_category?categoryLabels[m.visit_category]:'Equipo pendiente de configurar'}</p></div><div className="flex items-center gap-3"><span className="text-sm">{m.role==='supervisor'?'Supervisor':'Visitador'}</span><Badge value={m.active?'Activo':'Desactivado'}/>{<button className={secondary} disabled={busy||refreshing} onClick={()=>{setFormError('');setForm(m);}}>Editar</button>}</div></article>)}</div>}{invites.length>0&&<><h3 className="mt-8 border-t border-slate-100 pt-6 font-bold text-primary">Accesos pendientes</h3><p className="mt-1 text-sm text-slate-500">Se activan al verificar el correo e ingresar al seguimiento.</p>{invites.map(i=><article key={i.email} className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 py-4"><div><strong>{i.name}</strong><p className="break-all text-sm text-slate-500">{i.email} · {i.role}</p><p className="text-sm text-slate-500">{i.visit_category?categoryLabels[i.visit_category]:'Equipo pendiente de configurar'}</p></div><button className={secondary} onClick={()=>{setFormError('');setCancel(i.email);}}>Cancelar acceso</button></article>)}</>}</div>
 {form&&<Modal title={form==='new'?'Invitar integrante':'Editar acceso'} description={form==='new'?'Recibirá un correo para definir su contraseña.':form.email} busy={busy} onClose={()=>setForm(null)}><form onSubmit={save}><fieldset disabled={busy} className="grid gap-5">{form==='new'&&<><label className={label}>Nombre<input className={input} name="name" required minLength={2} maxLength={120}/></label><label className={label}>Correo<input className={input} name="email" type="email" required maxLength={254}/></label></>}<label className={label}>Rol<select className={input} name="role" disabled={form!=='new'&&form.id===me.id} defaultValue={form==='new'?'visitador':form.role}><option value="visitador">Visitador</option><option value="supervisor">Supervisor</option></select></label><label className={label}>Equipo de visitación<select className={input} name="category" defaultValue={form==='new'?'':form.visit_category??''}><option value="">Pendiente de configurar</option>{visitCategories.map(c=><option key={c} value={c}>{categoryLabels[c]}</option>)}</select><small className="font-normal text-slate-500">Sin equipo no se pueden asignar nuevas fichas. Al cambiarlo, las fichas clasificadas incompatibles quedarán sin responsable.</small></label>{form!=='new'&&form.id===me.id&&<Notice>Puedes configurar tu equipo. Tu rol y acceso se conservan.</Notice>}<Notice>El supervisor ve todas las visitas y gestiona el equipo. El visitador solo ve las visitas que registra.</Notice>{form!=='new'&&<label className={label}>Acceso<select className={input} name="active" disabled={form.id===me.id} defaultValue={String(form.active)}><option value="true">Activo</option><option value="false">Desactivado</option></select><small className="font-normal text-slate-500">Al desactivar, sus seguimientos quedan pendientes de reasignación y se conserva su historial.</small></label>}<ErrorNotice message={formError}/><div className="flex justify-end gap-3"><button className={secondary} type="button" onClick={()=>setForm(null)}>Cancelar</button><button className={button} disabled={busy} aria-busy={busy}>{busy?<BusyLabel>{form==='new'?'Enviando invitación…':'Guardando acceso…'}</BusyLabel>:form==='new'?'Enviar invitación':'Guardar acceso'}</button></div></fieldset></form></Modal>}
 {cancel&&<Modal title="Cancelar acceso pendiente" busy={busy} onClose={()=>setCancel(null)}><p>{cancel} no podrá incorporarse con esta invitación.</p><ErrorNotice message={formError}/><div className="mt-6 flex justify-end gap-3"><button className={secondary} disabled={busy} onClick={()=>setCancel(null)}>Volver</button><button className={button} disabled={busy} aria-busy={busy} onClick={()=>void cancelAccess()}>{busy?<BusyLabel>Cancelando acceso…</BusyLabel>:"Cancelar acceso"}</button></div></Modal>}
 </section>;
}
